apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo2
  name: demo2
spec:
  ports:
  - name: 8099-tcp
    port: 8099
    protocol: TCP
    targetPort: 8099
  selector:
    app: demo2
  sessionAffinity: None
  type: ClusterIP
